packages:
  - apps/*
  - packages/*

catalog:
  '@convex-dev/auth': 0.0.87
  '@radix-ui/react-slot': 1.2.3
  '@types/node': ^24.0.15
  '@types/react': ^19.1.8
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: ^1.26.2
  convex-helpers: ^0.1.104
  lucide-react: ^0.525.0
  postcss: ^8.5.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.5
  typescript: ^5.8.3

shared-workspace-lockfile: true
